#!/usr/bin/env python
import logging

import asyncio

from loan import DB

logging.basicConfig(
    format="{asctime} {levelname} [{name}:{lineno}] {message}",
    style='{',
    datefmt='%H:%M:%S',
    level='ERROR',
    handlers=[
        logging.StreamHandler(),
    ],
)


async def initialize_database():
    database = DB()
    await database.start()
    await database.init()

asyncio.run(initialize_database())
