#!/usr/bin/env python
import logging

import asyncio

from loan import DB

logging.basicConfig(
    format="{asctime} {levelname} [{name}:{lineno}] {message}",
    style='{',
    datefmt='%H:%M:%S',
    level='INFO',
    handlers=[
        logging.StreamHandler(),
    ],
)


async def main():
    database = DB()
    await database.start()
    await database.account_mensuality()

asyncio.run(main())